apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pvc-storageclass
  name: pvc-storageclass
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pvc-storageclass
  template:
    metadata:
      labels:
        app: pvc-storageclass
    spec:
      containers:
      - image: nginx
        name: pvc-storageclass
        volumeMounts:
        - name: data
          mountPath: /usr/share/nginx/html
      volumes:
      - name: data
        persistentVolumeClaim:					##调用哪个PVC
          claimName: my-pvc2-storageclass			##PVC的名称
---						
apiVersion: v1
kind: PersistentVolumeClaim		##创建PVC
metadata:
  name: my-pvc2-storageclass
spec:
  storageClassName: nfs-client		##指定sc，意思是调用sc去创建pv
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi

