apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod
spec:
  containers:
  - name: write
    image: centos
    command: ["bash","-c","for i in {1..100};do echo $i >> /data/hello;sleep 4;done"]
    volumeMounts:
      - name: data			##用于挂载的卷的名称，下面volumes的name
        mountPath: /data		##本容器挂载的目录，即本容器里面的目录/data
  - name: read
    image: centos
    command: ["bash","-c","tail -f /data/hello"]
    volumeMounts:
      - name: data
        mountPath: /data
  volumes:
  - name: data		##定义卷的名称
    emptyDir: {}		##使用emptyDir  ， {}代表空值

