apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
  - name: hostpath-pod
    image: centos
    command: ["bash","-c","sleep 36000"]
    volumeMounts:
      - name: data
        mountPath: /data
  volumes:
  - name: data
    hostPath:
      path: /tmp			##把宿主机/tmp目录，挂载到容器/data
      type: Directory		##指定类型，目录或文件

