apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  namespace: k8s
  labels:
    name: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      name: front-end
  template:
    metadata:
      labels:
        name: front-end
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2

